### ISSUE TITLE
Vereshtchagin or Vereshchagin?

### ISSUE THREAD

**Issue by gshguru** [standardebooks/anton-chekhov_the-duel_constance-garnett#1]
https://github.com/standardebooks/anton-chekhov_the-duel_constance-garnett/blob/15e3b7c52917c56120d030db7a82f9bc656aa6d6/src/epub/text/chapter-1.xhtml#L52

Is there a typo in "Vereshtchagin"? 
Related wiki: https://en.wikipedia.org/wiki/Vasily_Vereshchagin

**Comment by gshguru** [comment]
In some old references,  it looks like `t` has been used https://archive.org/details/vassiliverestcha01vereuoft/page/n7/mode/2up

**Comment by acabal** [comment]
Yes, it's common for Russian names to be transliterated in various ways across the years. We normalize some of the more famous ones like Tolstoy and Chekhov. I'll add this one to our list since he seems to be a prominent historical figure.
